# Generated by Django 6.0.5 on 2026-06-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goals',
            name='status',
            field=models.CharField(default=True),
        ),
    ]
